### ISSUE TITLE
Sweep: create a github action to perform angular tests before deployment

### ISSUE THREAD

**Issue by Polyterative** [Polyterative/Patcher#35]
I need setting up a GitHub Action workflow to run Angular my tests automatically before deploying to Vercel. Add action to default github path. ONLY ng tests. NO DEPLOY.

keep it simple

here is my not working draft as an example:
```

on:
  push:
    branches:
      - develop
  pull_request_target:
    types: [opened, synchronize, reopened]

name: Angular Tests

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      
      - name: Print environment variables
        run: printenv

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: ng test --verbose
```


<details open>
<summary>Checklist</summary>

- [X] `.github/workflows/angular-tests.yml` ✅ Commit [`30ffcc2`](https://github.com/Polyterative/Patcher/commit/30ffcc2260280852776b1bbd670888699ecd3f3e)
<blockquote>• Create a new file named angular-tests.yml in the .github/workflows directory.
• Add the "on" keyword to specify the events that trigger the workflow. Set it to trigger on push or pull request events on the develop branch.
• Add the "name" keyword to give the workflow a name. Set it to "Angular Tests".
• Add the "permissions" keyword to limit the permissions for the GITHUB_TOKEN. Set "contents" to "read" and "pull-requests" to "read".
• Add the "jobs" keyword to define the workflow jobs. Create a job named "test" that runs on the latest version of Ubuntu.
• Add steps to the "test" job to checkout the code, setup Node.js version 14, print environment variables, install dependencies using yarn, and run the Angular tests using the command "ng test --verbose".
<details open>
<summary>Sandbox Execution Logs</summary>

<blockquote>
<details >
<summary><code>trunk init</code> 1/3 ✓</summary>

<pre>⡿ Downloading Trunk 1.16.0...
⡿ Downloading Trunk 1.16.0...
⢿ Downloading Trunk 1.16.0...
⣻ Downloading Trunk 1.16.0...
⣽ Downloading Trunk 1.16.0...
⣾ Downloading Trunk 1.16.0...
⣷ Downloading Trunk 1.16.0...
✔ Downloading Trunk 1.16.0... done
⡿ Verifying Trunk sha256...
✔ Verifying Trunk sha256... done
⡿ Unpacking Trunk...
✔ Unpacking Trunk... done
































✔ 12 linters were enabled (.trunk/trunk.yaml)
  actionlint 1.6.25 (3 github-workflow files)
  checkov 2.4.9 (26 json, 4 yaml files)
  eslint 8.49.0 (1 javascript, 281 typescript files)
  git-diff-check (654 files)
  markdownlint 0.36.0 (5 markdown files) (created .markdownlint.yaml)
  osv-scanner 1.4.0 (2 lockfile files)
  oxipng 8.0.0 (15 png files)
  prettier 3.0.3 (1 css, 123 html, 1 javascript, 25 json, 5 markdown, 128 sass, 281 typescript, 4 yaml files)
  svgo 3.0.2 (36 svg files) (created svgo.config.js)
  trivy 0.45.1 (2 lockfile, 4 yaml files)
  trufflehog 3.56.1 (656 files)
  yamllint 1.32.0 (4 yaml files) (created .yamllint.yaml)
Next Steps
 1. Read documentation
    Our documentation can be found at https://docs.trunk.io
 2. Get help and give feedback
    Join the Trunk community at https://slack.trunk.io
</pre>
</details>



<details >
<summary><code>trunk fmt .github/workflows/angular-tests.yml</code> 2/3 ✓</summary>

<pre>



 ✔ Formatted .github/workflows/angular-tests.yml
Re-checking autofixed files...





Checked 1 file
✔ No issues
</pre>
</details>



<details open>
<summary><code>trunk check --fix .github/workflows/angular-tests.yml</code> 3/3 ✓</summary>

<pre>





















































































































































































































Checked 1 file
✔ No issues
</pre>
</details>
</blockquote>
</details>
</blockquote>

</details>
